#ifndef __TYPE_H__
#define __TYPE_H__

enum Type {
    NODE,
    STATEMENT,
    BLOCK,
    EXPRESSION,

    ASSIGNEXPRESSION,
    ADDEXPRESSION,
    SUBEXPRESSION,
    MULEXPRESSION,
    DIVEXPRESSION,
    ADDASSIGNEXPRESSION,
    SUBASSIGNEXPRESSION,
    MULASSIGNEXPRESSION,
    DIVASSIGNEXPRESSION,
    IDEXPRESSION,

    IDENTIFIER,
    DECLARATION,
    VARIABLEDECLARATION,
    FUNCTIONDECLARATION,
    CLASSDECLARATION,

    LOGICSTATEMENT,
    IFSTATEMENT,
    FORSTATEMENT,
    WHILESTATEMENT,

    INT,
    LONG,
    FLOAT,
    DOUBLE,
    BOOLEAN,
    CHAR,
    CLASS

};

#endif