#ifndef __TYPE_H__
#define __TYPE_H__

enum Type {
    NODE,

    BLOCK,

    EXPRESSION,
    IDENTIFIER,
    FUNCCALLEXPRESSION,
    ARITHMETICEXPRESSION,
    BINARYOPERATOR,
    UNARYOPERATOR,
    TYPECONVERTOPERATOR,
    CLASSEXPRESSION,
    CLASSVARIABLEEXPRESSION,
    CLASSFUNCEXPRESSION,
    ASSIGNEXPRESSION,
    VARIABLEASSIGN,
    ENTITYEXPRESSION,
    ARRAYASSIGN,
    CLASSASSIGN,

    DECLARATION,
    VARIABLEDECLARATION,
    FUNCTIONDECLARATION,
    CLASSDECLARATION,
    INTERFACEDECLARATION,

    STATEMENT,
    LOGICSTATEMENT,
    IFSTATEMENT,
    FORSTATEMENT,
    WHILESTATEMENT,

    INT,
    LONG,
    FLOAT,
    DOUBLE,
    BOOLEAN,
    CHAR,
    FUNC,
    VOID,
    ARRAY,
    CLASS,
    TYPE,
    NAME,
    VALUE,

    ERROR
};

#endif